// @generated by protoc-gen-connect-web v0.2.1 with parameter "target=ts"
// @generated from file schemas/v1/chat.proto (package schemas.v1, syntax proto3)
/* eslint-disable */
/* @ts-nocheck */

import {ChatRequest, ChatResponse} from "./chat_pb.js";
import {MethodKind} from "@bufbuild/protobuf";

/**
 * @generated from service schemas.v1.ChatService
 */
export const ChatService = {
  typeName: "schemas.v1.ChatService",
  methods: {
    /**
     * @generated from rpc schemas.v1.ChatService.send
     */
    send: {
      name: "send",
      I: ChatRequest,
      O: ChatResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc schemas.v1.ChatService.read
     */
    read: {
      name: "read",
      I: ChatRequest,
      O: ChatResponse,
      kind: MethodKind.ServerStreaming,
    },
  }
} as const;

